services:
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    networks:
      - internal
    volumes: 
      - ./grafana_data:/var/lib/grafana

  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3-core
    networks:
      - internal
    ports:
      - 8181:8181
    volumes:
      - ./influxdb/entrypoint.sh:/entrypoint.sh
    command: 
      - /entrypoint.sh

  campaign-manager:
    container_name: campaign-manager
    build: 
      context: ./campaign_manager
    environment:
      - INFLUXDB_HOST=http://influxdb3-core:8181
      - INFLUXDB_DATABASE=grafana
    networks:
      - internal
    ports:
      - 5000:5000

  mqtt-forwarder:
    container_name: mqtt-forwarder
    build: 
      context: ./mqtt_forwarder
    environment:
      - INFLUXDB_HOST=http://influxdb3-core:8181
      - INFLUXDB_DATABASE=grafana
      - MQTT_TOPIC=logger/#
      - MQTT_BROKER=localhost
      - MQTT_PORT=1883
    networks:
      - internal

networks:
  internal:
    driver: bridge

