FROM python:3-alpine

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY vehicleSignalSender.py vehicleSignalSender.py

ENV VEHICLE_ID="VIN0001"
ENV APP="logger"
ENV APP_VERSION="v2"
ENV MIN_MEASURED_VALUE="120"
ENV MAX_MEASURED_VALUE="150"

CMD ["python", "./vehicleSignalSender.py"]
