{
 "title": "battery_consumption_per_hour",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "version_EV001",
    "query": {
     "query": "SELECT COALESCE(version, \"VERSION\")\nFROM ev\nWHERE vehicle_id = 'EV-001'\nORDER BY time DESC\nLIMIT 1;"
    }
   },
   {
    "name": "version_EV002",
    "query": {
     "query": "SELECT COALESCE(version, \"VERSION\")\nFROM ev\nWHERE vehicle_id = 'EV-002'\nORDER BY time DESC\nLIMIT 1;"
    }
   },
   {
    "name": "version_EV003",
    "query": {
     "query": "SELECT COALESCE(version, \"VERSION\")\nFROM ev\nWHERE vehicle_id = 'EV-003'\nORDER BY time DESC\nLIMIT 1;"
    }
   },
   {
    "name": "version_EV004",
    "query": {
     "query": "SELECT COALESCE(version, \"VERSION\")\nFROM ev\nWHERE vehicle_id = 'EV-004'\nORDER BY time DESC\nLIMIT 1;"
    }
   },
   {
    "name": "version_EV005",
    "query": {
     "query": "SELECT COALESCE(version, \"VERSION\")\nFROM ev\nWHERE vehicle_id = 'EV-005'\nORDER BY time DESC\nLIMIT 1;"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "battery_consumption_per_hour",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  date_bin(INTERVAL '5 seconds', time) AS \"time\",\n  AVG(battery_consumption_per_hour)    AS \"value\",\n  COALESCE(version, \"VERSION\")         AS \"metric\"\nFROM ev\nWHERE $__timeFilter(time)\nGROUP BY \"time\", \"metric\"\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "EV-001 (${version_EV001})",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  battery_consumption_per_hour AS value\nFROM ev\nWHERE $__timeFilter(time) AND vehicle_id = 'EV-001'\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "EV-002 (${version_EV002})",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  battery_consumption_per_hour AS value,\n  concat(vehicle_id, ' ', COALESCE(version, \"VERSION\")) AS metric\nFROM ev\nWHERE $__timeFilter(time) AND vehicle_id = 'EV-002'\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "EV-003 (${version_EV003})",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  battery_consumption_per_hour AS value\nFROM ev\nWHERE $__timeFilter(time) AND vehicle_id = 'EV-003'\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "EV-004 (${version_EV004})",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  battery_consumption_per_hour AS value\nFROM ev\nWHERE $__timeFilter(time) AND vehicle_id = 'EV-004'\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "EV-005 (${version_EV005})",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  battery_consumption_per_hour AS value\nFROM ev\nWHERE $__timeFilter(time) AND vehicle_id = 'EV-005'\nORDER BY time DESC\nLIMIT 1;"
    }
   ]
  }
 ]
}