version: '3.4'

services:
  campaign-builder:
    image: campaign-builer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000